DROP TABLE IF EXISTS Matricula
create table Matricula ( id INT PRIMARY KEY, idProfesorado INT, idAlumnado INT, Asignatura VARCHAR(50), Curso INT, FOREIGN KEY (idProfesorado) REFERENCES Profesores(id), FOREIGN KEY (idAlumnado) REFERENCES Alumnado(id))
 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (1, 137, 25, 'Marketing', 3) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (2, 187, 138, 'Human Resources', 11) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (3, 46, 37, 'Engineering', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (4, 59, 23, 'Product Management', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (5, 39, 78, 'Engineering', 9) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (6, 90, 9, 'Business Development', 7) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (7, 50, 31, 'Business Development', 8) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (8, 178, 44, 'Support', 7) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (9, 49, 63, 'Legal', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (10, 17, 166, 'Legal', 6) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (11, 159, 186, 'Training', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (12, 168, 182, 'Legal', 9) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (13, 183, 193, 'Business Development', 12) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (14, 72, 19, 'Engineering', 3) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (15, 98, 45, 'Engineering', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (16, 91, 150, 'Accounting', 5) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (17, 188, 151, 'Sales', 8) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (18, 133, 194, 'Training', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (19, 181, 173, 'Research and Development', 10) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (20, 165, 95, 'Accounting', 11) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (21, 173, 103, 'Legal', 5) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (22, 6, 14, 'Marketing', 12) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (23, 85, 199, 'Product Management', 7) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (24, 126, 175, 'Human Resources', 5) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (25, 21, 166, 'Accounting', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (26, 2, 91, 'Business Development', 6) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (27, 48, 102, 'Sales', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (28, 82, 65, 'Business Development', 12) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (29, 49, 14, 'Research and Development', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (30, 158, 52, 'Training', 6) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (31, 47, 167, 'Training', 6) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (32, 46, 155, 'Training', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (33, 84, 86, 'Product Management', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (34, 138, 141, 'Research and Development', 5) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (35, 190, 146, 'Engineering', 12) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (36, 42, 111, 'Training', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (37, 187, 160, 'Services', 6) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (38, 4, 135, 'Sales', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (39, 160, 176, 'Legal', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (40, 151, 114, 'Training', 8) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (41, 10, 19, 'Product Management', 8) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (42, 194, 62, 'Training', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (43, 67, 150, 'Marketing', 3) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (44, 192, 138, 'Sales', 3) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (45, 163, 129, 'Human Resources', 11) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (46, 114, 23, 'Support', 12) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (47, 40, 186, 'Training', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (48, 104, 125, 'Engineering', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (49, 190, 145, 'Accounting', 12) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (50, 16, 99, 'Human Resources', 5) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (51, 79, 137, 'Legal', 10) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (52, 144, 184, 'Human Resources', 10) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (53, 185, 155, 'Services', 10) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (54, 140, 50, 'Legal', 11) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (55, 133, 121, 'Services', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (56, 78, 65, 'Training', 6) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (57, 126, 42, 'Research and Development', 11) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (58, 28, 127, 'Training', 5) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (59, 134, 124, 'Support', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (60, 17, 169, 'Human Resources', 7) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (61, 118, 24, 'Engineering', 5) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (62, 10, 51, 'Product Management', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (63, 48, 87, 'Research and Development', 9) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (64, 86, 199, 'Human Resources', 7) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (65, 90, 200, 'Research and Development', 10) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (66, 32, 88, 'Product Management', 9) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (67, 125, 87, 'Accounting', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (68, 155, 198, 'Product Management', 8) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (69, 95, 111, 'Sales', 8) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (70, 133, 55, 'Engineering', 8) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (71, 13, 196, 'Sales', 3) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (72, 158, 104, 'Human Resources', 8) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (73, 97, 183, 'Engineering', 7) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (74, 148, 130, 'Services', 12) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (75, 120, 29, 'Sales', 8) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (76, 171, 48, 'Research and Development', 9) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (77, 146, 51, 'Business Development', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (78, 128, 149, 'Product Management', 11) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (79, 60, 154, 'Marketing', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (80, 192, 136, 'Training', 7) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (81, 192, 8, 'Sales', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (82, 136, 36, 'Engineering', 12) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (83, 87, 165, 'Product Management', 8) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (84, 8, 3, 'Legal', 8) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (85, 25, 21, 'Training', 12) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (86, 30, 178, 'Business Development', 11) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (87, 101, 39, 'Support', 3) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (88, 100, 118, 'Training', 7) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (89, 118, 114, 'Business Development', 7) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (90, 163, 35, 'Legal', 9) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (91, 41, 199, 'Legal', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (92, 116, 52, 'Engineering', 5) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (93, 18, 39, 'Research and Development', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (94, 43, 98, 'Sales', 9) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (95, 137, 199, 'Training', 8) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (96, 62, 74, 'Sales', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (97, 76, 146, 'Support', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (98, 108, 140, 'Legal', 5) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (99, 161, 79, 'Marketing', 6) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (100, 144, 30, 'Legal', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (101, 56, 198, 'Services', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (102, 49, 139, 'Legal', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (103, 152, 190, 'Legal', 5) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (104, 80, 152, 'Human Resources', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (105, 137, 13, 'Accounting', 3) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (106, 193, 134, 'Support', 5) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (107, 4, 185, 'Sales', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (108, 102, 36, 'Product Management', 9) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (109, 36, 38, 'Product Management', 6) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (110, 31, 148, 'Research and Development', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (111, 43, 92, 'Research and Development', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (112, 127, 166, 'Engineering', 7) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (113, 131, 52, 'Human Resources', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (114, 75, 135, 'Accounting', 12) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (115, 179, 139, 'Support', 11) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (116, 181, 24, 'Business Development', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (117, 160, 140, 'Business Development', 11) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (118, 48, 68, 'Business Development', 10) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (119, 109, 122, 'Engineering', 5) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (120, 56, 43, 'Human Resources', 6) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (121, 28, 103, 'Accounting', 8) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (122, 118, 100, 'Accounting', 3) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (123, 144, 117, 'Product Management', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (124, 105, 105, 'Research and Development', 11) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (125, 144, 176, 'Services', 7) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (126, 37, 133, 'Services', 5) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (127, 195, 173, 'Services', 6) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (128, 69, 146, 'Sales', 5) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (129, 175, 78, 'Sales', 8) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (130, 20, 158, 'Legal', 5) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (131, 144, 32, 'Accounting', 7) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (132, 52, 162, 'Services', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (133, 17, 6, 'Product Management', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (134, 128, 189, 'Services', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (135, 8, 191, 'Accounting', 3) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (136, 159, 153, 'Product Management', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (137, 123, 122, 'Accounting', 9) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (138, 46, 160, 'Product Management', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (139, 169, 30, 'Support', 5) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (140, 44, 95, 'Business Development', 12) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (141, 13, 104, 'Research and Development', 12) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (142, 192, 2, 'Services', 10) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (143, 173, 142, 'Product Management', 8) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (144, 2, 24, 'Marketing', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (145, 43, 45, 'Engineering', 3) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (146, 137, 82, 'Training', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (147, 155, 199, 'Engineering', 9) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (148, 193, 159, 'Accounting', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (149, 47, 96, 'Product Management', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (150, 18, 141, 'Training', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (151, 91, 5, 'Product Management', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (152, 138, 46, 'Human Resources', 6) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (153, 155, 106, 'Legal', 6) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (154, 136, 181, 'Human Resources', 6) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (155, 102, 153, 'Research and Development', 9) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (156, 153, 200, 'Accounting', 12) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (157, 129, 12, 'Training', 9) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (158, 132, 181, 'Engineering', 5) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (159, 31, 193, 'Human Resources', 12) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (160, 141, 159, 'Marketing', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (161, 73, 169, 'Sales', 8) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (162, 59, 170, 'Accounting', 3) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (163, 175, 54, 'Services', 10) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (164, 177, 90, 'Business Development', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (165, 99, 85, 'Accounting', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (166, 68, 56, 'Services', 9) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (167, 11, 128, 'Services', 6) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (168, 6, 138, 'Marketing', 12) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (169, 33, 118, 'Sales', 3) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (170, 66, 192, 'Legal', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (171, 172, 48, 'Marketing', 7) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (172, 182, 136, 'Engineering', 9) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (173, 7, 198, 'Research and Development', 10) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (174, 140, 46, 'Training', 11) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (175, 118, 103, 'Training', 6) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (176, 91, 93, 'Product Management', 11) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (177, 11, 21, 'Engineering', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (178, 108, 50, 'Sales', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (179, 120, 111, 'Training', 10) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (180, 97, 111, 'Research and Development', 3) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (181, 15, 42, 'Marketing', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (182, 144, 133, 'Human Resources', 3) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (183, 19, 49, 'Services', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (184, 93, 164, 'Research and Development', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (185, 130, 106, 'Support', 11) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (186, 72, 24, 'Sales', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (187, 23, 81, 'Services', 10) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (188, 7, 112, 'Business Development', 3) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (189, 93, 35, 'Engineering', 12) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (190, 178, 68, 'Product Management', 4) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (191, 171, 14, 'Services', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (192, 198, 105, 'Marketing', 11) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (193, 144, 122, 'Sales', 6) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (194, 137, 93, 'Services', 11) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (195, 29, 142, 'Services', 12) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (196, 197, 78, 'Marketing', 1) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (197, 188, 23, 'Business Development', 9) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (198, 65, 165, 'Sales', 2) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (199, 44, 150, 'Product Management', 9) 
insert into Matricula (id, idProfesorado, idAlumnado, Asignatura, Curso) values (200, 106, 60, 'Product Management', 10) 
